# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths: 
       - '**/Si_*/**'
       - '!*.md'
  pull_request:
    branches: [ "main" ]

jobs:

  generateInputPaths:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Generate matrix with all modules of the repo
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(ls -l | grep '^d' | awk -F ' ' '{print $9}' | grep -Po 'Si.*' | jq -R -s -c 'split("\n") | map(select(length > 0))')"
          
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  checklinks:
    needs: generateInputPaths
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.generateInputPaths.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: Print Directory Structure
        run: |
           ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
     
  build:
    needs: generateInputPaths
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.generateInputPaths.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd ${{ matrix.path }}
        dotnet restore
    - name: Build
      run: |
        cd ${{ matrix.path }}
        dotnet build --no-restore
    - name: Test
      run: |
        cd ${{ matrix.path }}
        dotnet test --no-build --verbosity normal
